project:
  type: website

website:
  title: "Dr. Ethan Alt"
  sidebar:
    tools: 
      - icon: twitter
        href: https://twitter.com/drethanalt
      - icon: linkedin
        href: https://www.linkedin.com/in/ethanalt
      - icon: github
        href: https://www.github.com/ethan-alt
    style: "docked"
    search: true
    contents:
      - text: Home
        file: index.qmd
      - text: About me
        file: about.qmd
      - text: CV
        href: https://www.overleaf.com/read/pghtrskfypjt
      - text: Research
        file: research.qmd
      - text: Talks
        file: talks.qmd
      - text: Software
        file: software.qmd

format:
  html:
    link-external-newwindow: true
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: false

editor: visual

